version: '3'

services:

  elastic-srv:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    restart: always
    logging:
      options:
        max-size: 50m

  item-srv:
    image: item:latest
    ports:
      - "1234:1234"
      - "8080:8080"
    restart: always
    logging:
      options:
        max-size: 50m




