// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler.proto

package proto3

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaveItemRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveItemRequest) Reset()         { *m = SaveItemRequest{} }
func (m *SaveItemRequest) String() string { return proto.CompactTextString(m) }
func (*SaveItemRequest) ProtoMessage()    {}
func (*SaveItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{0}
}

func (m *SaveItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveItemRequest.Unmarshal(m, b)
}
func (m *SaveItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveItemRequest.Marshal(b, m, deterministic)
}
func (m *SaveItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveItemRequest.Merge(m, src)
}
func (m *SaveItemRequest) XXX_Size() int {
	return xxx_messageInfo_SaveItemRequest.Size(m)
}
func (m *SaveItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveItemRequest proto.InternalMessageInfo

func (m *SaveItemRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type SaveItemResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveItemResult) Reset()         { *m = SaveItemResult{} }
func (m *SaveItemResult) String() string { return proto.CompactTextString(m) }
func (*SaveItemResult) ProtoMessage()    {}
func (*SaveItemResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{1}
}

func (m *SaveItemResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveItemResult.Unmarshal(m, b)
}
func (m *SaveItemResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveItemResult.Marshal(b, m, deterministic)
}
func (m *SaveItemResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveItemResult.Merge(m, src)
}
func (m *SaveItemResult) XXX_Size() int {
	return xxx_messageInfo_SaveItemResult.Size(m)
}
func (m *SaveItemResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveItemResult.DiscardUnknown(m)
}

var xxx_messageInfo_SaveItemResult proto.InternalMessageInfo

type ProcessRequest struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	SerializedParser     *SerializedParser `protobuf:"bytes,2,opt,name=serializedParser,proto3" json:"serializedParser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProcessRequest) Reset()         { *m = ProcessRequest{} }
func (m *ProcessRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessRequest) ProtoMessage()    {}
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{2}
}

func (m *ProcessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessRequest.Unmarshal(m, b)
}
func (m *ProcessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessRequest.Marshal(b, m, deterministic)
}
func (m *ProcessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessRequest.Merge(m, src)
}
func (m *ProcessRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessRequest.Size(m)
}
func (m *ProcessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessRequest proto.InternalMessageInfo

func (m *ProcessRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ProcessRequest) GetSerializedParser() *SerializedParser {
	if m != nil {
		return m.SerializedParser
	}
	return nil
}

type SerializedParser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializedParser) Reset()         { *m = SerializedParser{} }
func (m *SerializedParser) String() string { return proto.CompactTextString(m) }
func (*SerializedParser) ProtoMessage()    {}
func (*SerializedParser) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{3}
}

func (m *SerializedParser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializedParser.Unmarshal(m, b)
}
func (m *SerializedParser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializedParser.Marshal(b, m, deterministic)
}
func (m *SerializedParser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializedParser.Merge(m, src)
}
func (m *SerializedParser) XXX_Size() int {
	return xxx_messageInfo_SerializedParser.Size(m)
}
func (m *SerializedParser) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializedParser.DiscardUnknown(m)
}

var xxx_messageInfo_SerializedParser proto.InternalMessageInfo

func (m *SerializedParser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SerializedParser) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type ProcessResult struct {
	Item                 []*Item           `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	Request              []*ProcessRequest `protobuf:"bytes,2,rep,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProcessResult) Reset()         { *m = ProcessResult{} }
func (m *ProcessResult) String() string { return proto.CompactTextString(m) }
func (*ProcessResult) ProtoMessage()    {}
func (*ProcessResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{4}
}

func (m *ProcessResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessResult.Unmarshal(m, b)
}
func (m *ProcessResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessResult.Marshal(b, m, deterministic)
}
func (m *ProcessResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessResult.Merge(m, src)
}
func (m *ProcessResult) XXX_Size() int {
	return xxx_messageInfo_ProcessResult.Size(m)
}
func (m *ProcessResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessResult proto.InternalMessageInfo

func (m *ProcessResult) GetItem() []*Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ProcessResult) GetRequest() []*ProcessRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type Item struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Payload              *Profile `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Car                  *Car     `protobuf:"bytes,5,opt,name=car,proto3" json:"car,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{5}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Item) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetPayload() *Profile {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Item) GetCar() *Car {
	if m != nil {
		return m.Car
	}
	return nil
}

type Profile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender               string   `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Weight               int32    `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Income               string   `protobuf:"bytes,6,opt,name=income,proto3" json:"income,omitempty"`
	Marriage             string   `protobuf:"bytes,7,opt,name=marriage,proto3" json:"marriage,omitempty"`
	Education            string   `protobuf:"bytes,8,opt,name=education,proto3" json:"education,omitempty"`
	Occupation           string   `protobuf:"bytes,9,opt,name=occupation,proto3" json:"occupation,omitempty"`
	Hokou                string   `protobuf:"bytes,10,opt,name=hokou,proto3" json:"hokou,omitempty"`
	Xinzuo               string   `protobuf:"bytes,11,opt,name=xinzuo,proto3" json:"xinzuo,omitempty"`
	House                string   `protobuf:"bytes,12,opt,name=house,proto3" json:"house,omitempty"`
	Car                  string   `protobuf:"bytes,13,opt,name=car,proto3" json:"car,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{6}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Profile) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Profile) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Profile) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Profile) GetIncome() string {
	if m != nil {
		return m.Income
	}
	return ""
}

func (m *Profile) GetMarriage() string {
	if m != nil {
		return m.Marriage
	}
	return ""
}

func (m *Profile) GetEducation() string {
	if m != nil {
		return m.Education
	}
	return ""
}

func (m *Profile) GetOccupation() string {
	if m != nil {
		return m.Occupation
	}
	return ""
}

func (m *Profile) GetHokou() string {
	if m != nil {
		return m.Hokou
	}
	return ""
}

func (m *Profile) GetXinzuo() string {
	if m != nil {
		return m.Xinzuo
	}
	return ""
}

func (m *Profile) GetHouse() string {
	if m != nil {
		return m.House
	}
	return ""
}

func (m *Profile) GetCar() string {
	if m != nil {
		return m.Car
	}
	return ""
}

type Car struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	ImageURL             string   `protobuf:"bytes,3,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	Size                 string   `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Fuel                 float32  `protobuf:"fixed32,5,opt,name=fuel,proto3" json:"fuel,omitempty"`
	Transmission         string   `protobuf:"bytes,6,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Engine               string   `protobuf:"bytes,7,opt,name=engine,proto3" json:"engine,omitempty"`
	Displacement         float32  `protobuf:"fixed32,8,opt,name=displacement,proto3" json:"displacement,omitempty"`
	MaxSpeed             float32  `protobuf:"fixed32,9,opt,name=maxSpeed,proto3" json:"maxSpeed,omitempty"`
	Acceleration         float32  `protobuf:"fixed32,10,opt,name=acceleration,proto3" json:"acceleration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Car) Reset()         { *m = Car{} }
func (m *Car) String() string { return proto.CompactTextString(m) }
func (*Car) ProtoMessage()    {}
func (*Car) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{7}
}

func (m *Car) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Car.Unmarshal(m, b)
}
func (m *Car) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Car.Marshal(b, m, deterministic)
}
func (m *Car) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Car.Merge(m, src)
}
func (m *Car) XXX_Size() int {
	return xxx_messageInfo_Car.Size(m)
}
func (m *Car) XXX_DiscardUnknown() {
	xxx_messageInfo_Car.DiscardUnknown(m)
}

var xxx_messageInfo_Car proto.InternalMessageInfo

func (m *Car) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Car) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Car) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func (m *Car) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Car) GetFuel() float32 {
	if m != nil {
		return m.Fuel
	}
	return 0
}

func (m *Car) GetTransmission() string {
	if m != nil {
		return m.Transmission
	}
	return ""
}

func (m *Car) GetEngine() string {
	if m != nil {
		return m.Engine
	}
	return ""
}

func (m *Car) GetDisplacement() float32 {
	if m != nil {
		return m.Displacement
	}
	return 0
}

func (m *Car) GetMaxSpeed() float32 {
	if m != nil {
		return m.MaxSpeed
	}
	return 0
}

func (m *Car) GetAcceleration() float32 {
	if m != nil {
		return m.Acceleration
	}
	return 0
}

func init() {
	proto.RegisterType((*SaveItemRequest)(nil), "proto3.SaveItemRequest")
	proto.RegisterType((*SaveItemResult)(nil), "proto3.SaveItemResult")
	proto.RegisterType((*ProcessRequest)(nil), "proto3.ProcessRequest")
	proto.RegisterType((*SerializedParser)(nil), "proto3.SerializedParser")
	proto.RegisterType((*ProcessResult)(nil), "proto3.ProcessResult")
	proto.RegisterType((*Item)(nil), "proto3.Item")
	proto.RegisterType((*Profile)(nil), "proto3.Profile")
	proto.RegisterType((*Car)(nil), "proto3.Car")
}

func init() { proto.RegisterFile("crawler.proto", fileDescriptor_84c7eabcfe7807d1) }

var fileDescriptor_84c7eabcfe7807d1 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xcf, 0x6e, 0xdb, 0x3e,
	0x0c, 0xfe, 0xc5, 0x49, 0x9a, 0x9a, 0x4d, 0xdb, 0x40, 0xe8, 0xaf, 0x13, 0x8a, 0x6d, 0x28, 0x7c,
	0xda, 0x2e, 0xc5, 0xd0, 0xde, 0x0a, 0xec, 0xd4, 0x5d, 0x06, 0xec, 0x50, 0x28, 0xd8, 0x03, 0x68,
	0x32, 0xeb, 0x08, 0xf3, 0xbf, 0x49, 0x76, 0xff, 0x3d, 0xc0, 0x80, 0x9d, 0xf7, 0x40, 0x7b, 0xb5,
	0x81, 0x94, 0xed, 0x26, 0x6d, 0x76, 0x32, 0xf9, 0xf1, 0x23, 0x45, 0x7e, 0xb4, 0x04, 0xfb, 0xc6,
	0xe9, 0xbb, 0x1c, 0xdd, 0x59, 0xed, 0xaa, 0xa6, 0x12, 0x3b, 0xfc, 0xb9, 0x48, 0x2e, 0xe0, 0x70,
	0xa9, 0x6f, 0xf1, 0x73, 0x83, 0x85, 0xc2, 0x1f, 0x2d, 0xfa, 0x46, 0x9c, 0xc2, 0xc4, 0x36, 0x58,
	0xc8, 0xd1, 0xe9, 0xe8, 0xdd, 0xde, 0xf9, 0x3c, 0x24, 0x5c, 0x9c, 0x31, 0x85, 0x23, 0xc9, 0x02,
	0x0e, 0x9e, 0x92, 0x7c, 0x9b, 0x37, 0xc9, 0x0a, 0x0e, 0xae, 0x5d, 0x65, 0xd0, 0xfb, 0xbe, 0xca,
	0x02, 0xc6, 0xad, 0xcb, 0xb9, 0x48, 0xac, 0xc8, 0x14, 0x9f, 0x60, 0xe1, 0xd1, 0x59, 0x9d, 0xdb,
	0x47, 0x4c, 0xaf, 0xb5, 0xf3, 0xe8, 0x64, 0xc4, 0x67, 0xc8, 0xfe, 0x8c, 0xe5, 0xb3, 0xb8, 0x7a,
	0x91, 0x91, 0x5c, 0xc2, 0xe2, 0x39, 0x4b, 0x08, 0x98, 0x94, 0xba, 0xc0, 0xee, 0x30, 0xb6, 0x09,
	0xd3, 0x2e, 0xf3, 0x7c, 0x42, 0xac, 0xd8, 0x4e, 0x0c, 0xec, 0x0f, 0x5d, 0x52, 0xdb, 0x6b, 0xa3,
	0x8e, 0xb7, 0x8f, 0x2a, 0x3e, 0xc0, 0xcc, 0x85, 0x89, 0x64, 0xc4, 0xa4, 0xe3, 0x9e, 0xb4, 0x39,
	0xaf, 0xea, 0x69, 0xc9, 0xcf, 0x11, 0x4c, 0xa8, 0xc0, 0x16, 0x05, 0x04, 0x4c, 0x9a, 0x87, 0x1a,
	0xfb, 0x9e, 0xc8, 0x16, 0x07, 0x10, 0xd9, 0x54, 0x8e, 0x19, 0x89, 0x6c, 0x2a, 0xde, 0xc3, 0xec,
	0x5a, 0x3f, 0xe4, 0x95, 0x4e, 0xe5, 0x84, 0xc5, 0x39, 0x5c, 0x3b, 0xf0, 0xc6, 0xe6, 0xa8, 0xfa,
	0xb8, 0x78, 0x03, 0x63, 0xa3, 0x9d, 0x9c, 0x32, 0x6d, 0xaf, 0xa7, 0x5d, 0x69, 0xa7, 0x08, 0x4f,
	0xfe, 0x44, 0x30, 0xeb, 0x72, 0xb6, 0x2a, 0x74, 0x0c, 0x3b, 0x19, 0x96, 0x69, 0xb7, 0x85, 0x58,
	0x75, 0x1e, 0xf5, 0xad, 0x33, 0xe4, 0x96, 0xa6, 0x8a, 0x4c, 0x62, 0xae, 0xd0, 0x66, 0xab, 0x86,
	0x5b, 0x9a, 0xaa, 0xce, 0x23, 0xfc, 0x2e, 0xe0, 0xd3, 0x80, 0xdf, 0x0d, 0xb8, 0x2d, 0x4d, 0x55,
	0xa0, 0xdc, 0x09, 0x95, 0x83, 0x27, 0x4e, 0x60, 0xb7, 0xd0, 0xce, 0x59, 0x2a, 0x3f, 0xe3, 0xc8,
	0xe0, 0x8b, 0xd7, 0x10, 0x63, 0xda, 0x1a, 0xdd, 0xd8, 0xaa, 0x94, 0xbb, 0x1c, 0x7c, 0x02, 0xc4,
	0x5b, 0x80, 0xca, 0x98, 0xb6, 0x0e, 0xe1, 0x98, 0xc3, 0x6b, 0x88, 0x38, 0x82, 0xe9, 0xaa, 0xfa,
	0x5e, 0xb5, 0x12, 0x38, 0x14, 0x1c, 0xea, 0xe3, 0xde, 0x96, 0x8f, 0x6d, 0x25, 0xf7, 0x42, 0x1f,
	0xc1, 0x0b, 0xec, 0xd6, 0xa3, 0x9c, 0xf7, 0xec, 0xd6, 0x23, 0xcd, 0x4d, 0x72, 0xee, 0x87, 0x7d,
	0x91, 0x82, 0xbf, 0x23, 0x18, 0x5f, 0xe9, 0xed, 0xff, 0xd7, 0x11, 0x4c, 0x6b, 0x67, 0x4d, 0x58,
	0x66, 0xa4, 0x82, 0x43, 0x13, 0xda, 0x42, 0x67, 0xf8, 0x55, 0x7d, 0xe9, 0x76, 0x3a, 0xf8, 0x54,
	0xc5, 0xdb, 0x47, 0x64, 0x0d, 0x63, 0xc5, 0x36, 0x61, 0x37, 0x2d, 0xe6, 0xac, 0x5f, 0xa4, 0xd8,
	0x16, 0x09, 0xcc, 0x1b, 0xa7, 0x4b, 0x5f, 0x58, 0xef, 0x69, 0xda, 0xa0, 0xe1, 0x06, 0x46, 0x93,
	0x61, 0x99, 0xd9, 0xb2, 0xd7, 0xb1, 0xf3, 0x28, 0x37, 0xb5, 0xbe, 0xce, 0xb5, 0xc1, 0x02, 0xcb,
	0x86, 0x85, 0x8c, 0xd4, 0x06, 0x16, 0xb6, 0x70, 0xbf, 0xac, 0x11, 0x53, 0x56, 0x32, 0x52, 0x83,
	0x4f, 0xf9, 0xda, 0x18, 0xcc, 0xd1, 0x05, 0xa5, 0x21, 0xe4, 0xaf, 0x63, 0xe7, 0xbf, 0x46, 0x30,
	0x5f, 0x36, 0x95, 0xc3, 0x25, 0xba, 0x5b, 0x1a, 0xfa, 0x23, 0xec, 0xf6, 0xcf, 0x81, 0x78, 0x35,
	0x5c, 0xe5, 0xcd, 0x57, 0xe5, 0xe4, 0xf8, 0x65, 0x80, 0x5f, 0x8e, 0xff, 0xc4, 0x25, 0xff, 0xa6,
	0x74, 0x97, 0xc4, 0x3f, 0x2e, 0xd7, 0xc9, 0xff, 0x2f, 0xf0, 0x90, 0xfb, 0xad, 0x7b, 0xc6, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xb0, 0x41, 0xa5, 0xde, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreServiceClient interface {
	SaveItem(ctx context.Context, in *SaveItemRequest, opts ...grpc.CallOption) (*SaveItemResult, error)
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResult, error)
}

type storeServiceClient struct {
	cc *grpc.ClientConn
}

func NewStoreServiceClient(cc *grpc.ClientConn) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) SaveItem(ctx context.Context, in *SaveItemRequest, opts ...grpc.CallOption) (*SaveItemResult, error) {
	out := new(SaveItemResult)
	err := c.cc.Invoke(ctx, "/proto3.StoreService/SaveItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResult, error) {
	out := new(ProcessResult)
	err := c.cc.Invoke(ctx, "/proto3.StoreService/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
type StoreServiceServer interface {
	SaveItem(context.Context, *SaveItemRequest) (*SaveItemResult, error)
	Process(context.Context, *ProcessRequest) (*ProcessResult, error)
}

func RegisterStoreServiceServer(s *grpc.Server, srv StoreServiceServer) {
	s.RegisterService(&_StoreService_serviceDesc, srv)
}

func _StoreService_SaveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).SaveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto3.StoreService/SaveItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).SaveItem(ctx, req.(*SaveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto3.StoreService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto3.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveItem",
			Handler:    _StoreService_SaveItem_Handler,
		},
		{
			MethodName: "Process",
			Handler:    _StoreService_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawler.proto",
}
